### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by TheDarkIceKing** [Crack3dC0d3/MinetopiaVehicles-Revamped#16]
**Beschrijf de bug**
voertuigen kunnen verdwijnen onder omstandigheden. Dit heeft te maken met uitloggen en restarts

**Reproduceren**
1. Pak een voertuig
2. Plaats het en ga erin zitten
3. Log uit van de server
4. Restart de server.
5. Log in.
Je zit dan in de lucht, de fiets is verdwenen. De "Seat" waar de speler in zat is nog aanwezig. De rest niet.

**Wat je verwacht dat er gebeurt**
Ik verwacht dat je uit het voertuig gegooid wordt. En dat deze niet zal glitchen na uitloggen/restart.

**Wat er gebeurt**
Alle armorstands behalve de seat waar de speler in zat verdwijnen. Zodra je deze armor stand weer wild berijden of als voertuig wil oppakken, een error komt in console.

**Screenshots**
Als screenshots het beeld van de bug/glitch/fout versterken graag bijvoegen.
![image](https://user-images.githubusercontent.com/67518900/85931212-eeee9200-b8c2-11ea-95b3-ec997e29c73d.png)

**Versies**
Server: 1.12.2
Plugin: 0.0.1d-BETA

**Opmerkingen**
Nog opmerkingen?
Indien je meer info of vragen hebt, ping of dm me even op discord

**Comment by TheDarkIceKing** [comment]
![image](https://user-images.githubusercontent.com/67518900/85931234-1e050380-b8c3-11ea-9f5c-31ec1bb05241.png)

**Comment by Crack3dC0d3** [comment]
Oh jeetje. Gaan we naar kijken :D

**Comment by Crack3dC0d3** [comment]
Kan je de vehicle.db sturen?

**Comment by TheDarkIceKing** [comment]
Hoe. Github support m niet. In een zip gooien?

**Comment by TheDarkIceKing** [comment]
[vehicles.zip](https://github.com/Crack3dC0d3/MinetopiaVehicles-Revamped/files/4841189/vehicles.zip)

**Comment by Crack3dC0d3** [comment]
Ik krijg het voor elkaar om de fiets kapot te glitchen alsin dat hij niet meer werkt maar bij mij verdwijnt hij niet?

**Comment by TheDarkIceKing** [comment]
ben je uitgelogd en heb je de server gekilled?

**Comment by Crack3dC0d3** [comment]
Lmz haha. Oppakken verkloot de boel

**Comment by Crack3dC0d3** [comment]
Fixed in 6c2f58b
